jobs:
  build:
    docker:
      - image: pchakraborty/plbpd-build-env:1.0.0
    working_directory: /root/project/bld
    steps:
      - checkout
      - run: $CXX --version && echo $HDF5_DIR && echo $TBBROOT && pwd && ls
      - run: mkdir bld
      - run: cmake -DCMAKE_BUILD_TYPE=Release ../src
      - run: make -j4
      - run: ctest -V
