jobs:
  build:
    docker:
      - image: pchakraborty/plbpd-build-env:1.0.0
    working_directory: /root/project
    steps:
      - checkout
      - run: $CXX --version && echo $HDF5_DIR && echo $TBBROOT
      - run: mkdir bld && cd bld
      - run: cmake -DCMAKE_BUILD_TYPE=Release ../src
      - run: make -j4
      - run: make test
